from enum import Enum


class PIIType(Enum):
    PERSON = "person"
    ORGANIZATION = "organization"
    PHONE_NUMBER = "phone number"
    ADDRESS = "address"
    PASSPORT_NUMBER = "passport number"
    EMAIL = "email"
    CREDIT_CARD_NUMBER = "credit card number"
    SOCIAL_SECURITY_NUMBER = "social security number"
    HEALTH_INSURANCE_ID_NUMBER = "health insurance id number"
    DATE_OF_BIRTH = "date of birth"
    MOBILE_PHONE_NUMBER = "mobile phone number"
    BANK_ACCOUNT_NUMBER = "bank account number"
    MEDICATION = "medication"
    CPF = "cpf"
    DRIVER_LICENSE_NUMBER = "driver's license number"
    TAX_IDENTIFICATION_NUMBER = "tax identification number"
    MEDICAL_CONDITION = "medical condition"
    IDENTITY_CARD_NUMBER = "identity card number"
    NATIONAL_ID_NUMBER = "national id number"
    IP_ADDRESS = "ip address"
    EMAIL_ADDRESS = "email address"
    IBAN = "iban"
    CREDIT_CARD_EXPIRATION_DATE = "credit card expiration date"
    USERNAME = "username"
    HEALTH_INSURANCE_NUMBER = "health insurance number"
    REGISTRATION_NUMBER = "registration number"
    STUDENT_ID_NUMBER = "student id number"
    INSURANCE_NUMBER = "insurance number"
    FLIGHT_NUMBER = "flight number"
    LANDLINE_PHONE_NUMBER = "landline phone number"
    BLOOD_TYPE = "blood type"
    CVV = "cvv"
    RESERVATION_NUMBER = "reservation number"
    DIGITAL_SIGNATURE = "digital signature"
    SOCIAL_MEDIA_HANDLE = "social media handle"
    LICENSE_PLATE_NUMBER = "license plate number"
    CNPJ = "cnpj"
    POSTAL_CODE = "postal code"
    SERIAL_NUMBER = "serial number"
    VEHICLE_REGISTRATION_NUMBER = "vehicle registration number"
    CREDIT_CARD_BRAND = "credit card brand"
    FAX_NUMBER = "fax number"
    VISA_NUMBER = "visa number"
    INSURANCE_COMPANY = "insurance company"
    IDENTITY_DOCUMENT_NUMBER = "identity document number"
    TRANSACTION_NUMBER = "transaction number"
    NATIONAL_HEALTH_INSURANCE_NUMBER = "national health insurance number"
    CVC = "cvc"
    BIRTH_CERTIFICATE_NUMBER = "birth certificate number"
    TRAIN_TICKET_NUMBER = "train ticket number"
    PASSPORT_EXPIRATION_DATE = "passport expiration date"

    @property
    def mask(self) -> str:
        """Return the bracketed placeholder for this PII type."""
        return f"[{self.value.upper()}]"
